/* eslint-disable */
import {
  CollectionCustomizer,
  TAggregation,
  TConditionTree,
  TPaginatedFilter,
  TPartialRow,
  TSortClause
} from '@forestadmin/agent';

export type AerichCustomizer = CollectionCustomizer<Schema, 'aerich'>;
export type AerichRecord = TPartialRow<Schema, 'aerich'>;
export type AerichConditionTree = TConditionTree<Schema, 'aerich'>;
export type AerichFilter = TPaginatedFilter<Schema, 'aerich'>;
export type AerichSortClause = TSortClause<Schema, 'aerich'>;
export type AerichAggregation = TAggregation<Schema, 'aerich'>;

export type EquipmentCustomizer = CollectionCustomizer<Schema, 'equipment'>;
export type EquipmentRecord = TPartialRow<Schema, 'equipment'>;
export type EquipmentConditionTree = TConditionTree<Schema, 'equipment'>;
export type EquipmentFilter = TPaginatedFilter<Schema, 'equipment'>;
export type EquipmentSortClause = TSortClause<Schema, 'equipment'>;
export type EquipmentAggregation = TAggregation<Schema, 'equipment'>;

export type EquipmentcategoryCustomizer = CollectionCustomizer<Schema, 'equipmentcategory'>;
export type EquipmentcategoryRecord = TPartialRow<Schema, 'equipmentcategory'>;
export type EquipmentcategoryConditionTree = TConditionTree<Schema, 'equipmentcategory'>;
export type EquipmentcategoryFilter = TPaginatedFilter<Schema, 'equipmentcategory'>;
export type EquipmentcategorySortClause = TSortClause<Schema, 'equipmentcategory'>;
export type EquipmentcategoryAggregation = TAggregation<Schema, 'equipmentcategory'>;

export type EquipmentdocumentCustomizer = CollectionCustomizer<Schema, 'equipmentdocument'>;
export type EquipmentdocumentRecord = TPartialRow<Schema, 'equipmentdocument'>;
export type EquipmentdocumentConditionTree = TConditionTree<Schema, 'equipmentdocument'>;
export type EquipmentdocumentFilter = TPaginatedFilter<Schema, 'equipmentdocument'>;
export type EquipmentdocumentSortClause = TSortClause<Schema, 'equipmentdocument'>;
export type EquipmentdocumentAggregation = TAggregation<Schema, 'equipmentdocument'>;

export type EquipmentmediaCustomizer = CollectionCustomizer<Schema, 'equipmentmedia'>;
export type EquipmentmediaRecord = TPartialRow<Schema, 'equipmentmedia'>;
export type EquipmentmediaConditionTree = TConditionTree<Schema, 'equipmentmedia'>;
export type EquipmentmediaFilter = TPaginatedFilter<Schema, 'equipmentmedia'>;
export type EquipmentmediaSortClause = TSortClause<Schema, 'equipmentmedia'>;
export type EquipmentmediaAggregation = TAggregation<Schema, 'equipmentmedia'>;

export type NotificationCustomizer = CollectionCustomizer<Schema, 'notification'>;
export type NotificationRecord = TPartialRow<Schema, 'notification'>;
export type NotificationConditionTree = TConditionTree<Schema, 'notification'>;
export type NotificationFilter = TPaginatedFilter<Schema, 'notification'>;
export type NotificationSortClause = TSortClause<Schema, 'notification'>;
export type NotificationAggregation = TAggregation<Schema, 'notification'>;

export type OrderCustomizer = CollectionCustomizer<Schema, 'order'>;
export type OrderRecord = TPartialRow<Schema, 'order'>;
export type OrderConditionTree = TConditionTree<Schema, 'order'>;
export type OrderFilter = TPaginatedFilter<Schema, 'order'>;
export type OrderSortClause = TSortClause<Schema, 'order'>;
export type OrderAggregation = TAggregation<Schema, 'order'>;

export type OrganizationCustomizer = CollectionCustomizer<Schema, 'organization'>;
export type OrganizationRecord = TPartialRow<Schema, 'organization'>;
export type OrganizationConditionTree = TConditionTree<Schema, 'organization'>;
export type OrganizationFilter = TPaginatedFilter<Schema, 'organization'>;
export type OrganizationSortClause = TSortClause<Schema, 'organization'>;
export type OrganizationAggregation = TAggregation<Schema, 'organization'>;

export type OwnerreviewCustomizer = CollectionCustomizer<Schema, 'ownerreview'>;
export type OwnerreviewRecord = TPartialRow<Schema, 'ownerreview'>;
export type OwnerreviewConditionTree = TConditionTree<Schema, 'ownerreview'>;
export type OwnerreviewFilter = TPaginatedFilter<Schema, 'ownerreview'>;
export type OwnerreviewSortClause = TSortClause<Schema, 'ownerreview'>;
export type OwnerreviewAggregation = TAggregation<Schema, 'ownerreview'>;

export type RenterreviewCustomizer = CollectionCustomizer<Schema, 'renterreview'>;
export type RenterreviewRecord = TPartialRow<Schema, 'renterreview'>;
export type RenterreviewConditionTree = TConditionTree<Schema, 'renterreview'>;
export type RenterreviewFilter = TPaginatedFilter<Schema, 'renterreview'>;
export type RenterreviewSortClause = TSortClause<Schema, 'renterreview'>;
export type RenterreviewAggregation = TAggregation<Schema, 'renterreview'>;

export type UserCustomizer = CollectionCustomizer<Schema, 'user'>;
export type UserRecord = TPartialRow<Schema, 'user'>;
export type UserConditionTree = TConditionTree<Schema, 'user'>;
export type UserFilter = TPaginatedFilter<Schema, 'user'>;
export type UserSortClause = TSortClause<Schema, 'user'>;
export type UserAggregation = TAggregation<Schema, 'user'>;


export type Schema = {
  'aerich': {
    plain: {
      'id': number;
      'version': string;
      'app': string;
      'content': any;
    };
    nested: {};
    flat: {};
  };
  'equipment': {
    plain: {
      'id': number;
      'name': string;
      'description': string;
      'description_of_configuration': string;
      'with_operator': boolean;
      'price': number;
      'time_interval': string;
      'status': string;
      'year_of_release': number;
      'created_at': string;
      'updated_at': string;
      'added_by_id': number;
      'category_id': number;
      'organization_id': string;
    };
    nested: {
      'added_by': Schema['user']['plain'] & Schema['user']['nested'];
      'category': Schema['equipmentcategory']['plain'] & Schema['equipmentcategory']['nested'];
      'organization': Schema['organization']['plain'] & Schema['organization']['nested'];
    };
    flat: {
      'added_by:id': number;
      'added_by:email': string;
      'added_by:is_owner': boolean;
      'added_by:hashed_password': string;
      'added_by:phone': string;
      'added_by:full_name': string;
      'added_by:disabled': boolean;
      'added_by:is_admin': boolean;
      'added_by:is_verified_organization_member': boolean;
      'added_by:created_at': string;
      'added_by:organization_inn': string;
      'added_by:organization:inn': string;
      'added_by:organization:short_name': string;
      'added_by:organization:full_name': string;
      'added_by:organization:ogrn': string;
      'added_by:organization:kpp': string;
      'added_by:organization:registration_date': string;
      'added_by:organization:authorized_capital_k_rubles': number;
      'added_by:organization:legal_address': string;
      'added_by:organization:manager_name': string;
      'added_by:organization:main_activity': string;
      'category:id': number;
      'category:name': string;
      'category:created_at': string;
      'category:verified': boolean;
      'category:added_by_id': number;
      'category:added_by:id': number;
      'category:added_by:email': string;
      'category:added_by:is_owner': boolean;
      'category:added_by:hashed_password': string;
      'category:added_by:phone': string;
      'category:added_by:full_name': string;
      'category:added_by:disabled': boolean;
      'category:added_by:is_admin': boolean;
      'category:added_by:is_verified_organization_member': boolean;
      'category:added_by:created_at': string;
      'category:added_by:organization_inn': string;
      'category:added_by:organization:inn': string;
      'category:added_by:organization:short_name': string;
      'category:added_by:organization:full_name': string;
      'category:added_by:organization:ogrn': string;
      'category:added_by:organization:kpp': string;
      'category:added_by:organization:registration_date': string;
      'category:added_by:organization:authorized_capital_k_rubles': number;
      'category:added_by:organization:legal_address': string;
      'category:added_by:organization:manager_name': string;
      'category:added_by:organization:main_activity': string;
      'organization:inn': string;
      'organization:short_name': string;
      'organization:full_name': string;
      'organization:ogrn': string;
      'organization:kpp': string;
      'organization:registration_date': string;
      'organization:authorized_capital_k_rubles': number;
      'organization:legal_address': string;
      'organization:manager_name': string;
      'organization:main_activity': string;
    };
  };
  'equipmentcategory': {
    plain: {
      'id': number;
      'name': string;
      'created_at': string;
      'verified': boolean;
      'added_by_id': number;
    };
    nested: {
      'added_by': Schema['user']['plain'] & Schema['user']['nested'];
    };
    flat: {
      'added_by:id': number;
      'added_by:email': string;
      'added_by:is_owner': boolean;
      'added_by:hashed_password': string;
      'added_by:phone': string;
      'added_by:full_name': string;
      'added_by:disabled': boolean;
      'added_by:is_admin': boolean;
      'added_by:is_verified_organization_member': boolean;
      'added_by:created_at': string;
      'added_by:organization_inn': string;
      'added_by:organization:inn': string;
      'added_by:organization:short_name': string;
      'added_by:organization:full_name': string;
      'added_by:organization:ogrn': string;
      'added_by:organization:kpp': string;
      'added_by:organization:registration_date': string;
      'added_by:organization:authorized_capital_k_rubles': number;
      'added_by:organization:legal_address': string;
      'added_by:organization:manager_name': string;
      'added_by:organization:main_activity': string;
    };
  };
  'equipmentdocument': {
    plain: {
      'id': number;
      'name': string;
      'media_type': string;
      'media_format': string;
      'hash': string;
      'original_path': string;
      'path': any;
      'created_at': string;
      'host_id': number;
    };
    nested: {
      'host': Schema['equipment']['plain'] & Schema['equipment']['nested'];
    };
    flat: {
      'host:id': number;
      'host:name': string;
      'host:description': string;
      'host:description_of_configuration': string;
      'host:with_operator': boolean;
      'host:price': number;
      'host:time_interval': string;
      'host:status': string;
      'host:year_of_release': number;
      'host:created_at': string;
      'host:updated_at': string;
      'host:added_by_id': number;
      'host:category_id': number;
      'host:organization_id': string;
      'host:added_by:id': number;
      'host:added_by:email': string;
      'host:added_by:is_owner': boolean;
      'host:added_by:hashed_password': string;
      'host:added_by:phone': string;
      'host:added_by:full_name': string;
      'host:added_by:disabled': boolean;
      'host:added_by:is_admin': boolean;
      'host:added_by:is_verified_organization_member': boolean;
      'host:added_by:created_at': string;
      'host:added_by:organization_inn': string;
      'host:added_by:organization:inn': string;
      'host:added_by:organization:short_name': string;
      'host:added_by:organization:full_name': string;
      'host:added_by:organization:ogrn': string;
      'host:added_by:organization:kpp': string;
      'host:added_by:organization:registration_date': string;
      'host:added_by:organization:authorized_capital_k_rubles': number;
      'host:added_by:organization:legal_address': string;
      'host:added_by:organization:manager_name': string;
      'host:added_by:organization:main_activity': string;
      'host:category:id': number;
      'host:category:name': string;
      'host:category:created_at': string;
      'host:category:verified': boolean;
      'host:category:added_by_id': number;
      'host:category:added_by:id': number;
      'host:category:added_by:email': string;
      'host:category:added_by:is_owner': boolean;
      'host:category:added_by:hashed_password': string;
      'host:category:added_by:phone': string;
      'host:category:added_by:full_name': string;
      'host:category:added_by:disabled': boolean;
      'host:category:added_by:is_admin': boolean;
      'host:category:added_by:is_verified_organization_member': boolean;
      'host:category:added_by:created_at': string;
      'host:category:added_by:organization_inn': string;
      'host:category:added_by:organization:inn': string;
      'host:category:added_by:organization:short_name': string;
      'host:category:added_by:organization:full_name': string;
      'host:category:added_by:organization:ogrn': string;
      'host:category:added_by:organization:kpp': string;
      'host:category:added_by:organization:registration_date': string;
      'host:category:added_by:organization:authorized_capital_k_rubles': number;
      'host:category:added_by:organization:legal_address': string;
      'host:category:added_by:organization:manager_name': string;
      'host:category:added_by:organization:main_activity': string;
      'host:organization:inn': string;
      'host:organization:short_name': string;
      'host:organization:full_name': string;
      'host:organization:ogrn': string;
      'host:organization:kpp': string;
      'host:organization:registration_date': string;
      'host:organization:authorized_capital_k_rubles': number;
      'host:organization:legal_address': string;
      'host:organization:manager_name': string;
      'host:organization:main_activity': string;
    };
  };
  'equipmentmedia': {
    plain: {
      'id': number;
      'name': string;
      'media_type': string;
      'media_format': string;
      'hash': string;
      'original_path': string;
      'path': any;
      'created_at': string;
      'host_id': number;
    };
    nested: {
      'host': Schema['equipment']['plain'] & Schema['equipment']['nested'];
    };
    flat: {
      'host:id': number;
      'host:name': string;
      'host:description': string;
      'host:description_of_configuration': string;
      'host:with_operator': boolean;
      'host:price': number;
      'host:time_interval': string;
      'host:status': string;
      'host:year_of_release': number;
      'host:created_at': string;
      'host:updated_at': string;
      'host:added_by_id': number;
      'host:category_id': number;
      'host:organization_id': string;
      'host:added_by:id': number;
      'host:added_by:email': string;
      'host:added_by:is_owner': boolean;
      'host:added_by:hashed_password': string;
      'host:added_by:phone': string;
      'host:added_by:full_name': string;
      'host:added_by:disabled': boolean;
      'host:added_by:is_admin': boolean;
      'host:added_by:is_verified_organization_member': boolean;
      'host:added_by:created_at': string;
      'host:added_by:organization_inn': string;
      'host:added_by:organization:inn': string;
      'host:added_by:organization:short_name': string;
      'host:added_by:organization:full_name': string;
      'host:added_by:organization:ogrn': string;
      'host:added_by:organization:kpp': string;
      'host:added_by:organization:registration_date': string;
      'host:added_by:organization:authorized_capital_k_rubles': number;
      'host:added_by:organization:legal_address': string;
      'host:added_by:organization:manager_name': string;
      'host:added_by:organization:main_activity': string;
      'host:category:id': number;
      'host:category:name': string;
      'host:category:created_at': string;
      'host:category:verified': boolean;
      'host:category:added_by_id': number;
      'host:category:added_by:id': number;
      'host:category:added_by:email': string;
      'host:category:added_by:is_owner': boolean;
      'host:category:added_by:hashed_password': string;
      'host:category:added_by:phone': string;
      'host:category:added_by:full_name': string;
      'host:category:added_by:disabled': boolean;
      'host:category:added_by:is_admin': boolean;
      'host:category:added_by:is_verified_organization_member': boolean;
      'host:category:added_by:created_at': string;
      'host:category:added_by:organization_inn': string;
      'host:category:added_by:organization:inn': string;
      'host:category:added_by:organization:short_name': string;
      'host:category:added_by:organization:full_name': string;
      'host:category:added_by:organization:ogrn': string;
      'host:category:added_by:organization:kpp': string;
      'host:category:added_by:organization:registration_date': string;
      'host:category:added_by:organization:authorized_capital_k_rubles': number;
      'host:category:added_by:organization:legal_address': string;
      'host:category:added_by:organization:manager_name': string;
      'host:category:added_by:organization:main_activity': string;
      'host:organization:inn': string;
      'host:organization:short_name': string;
      'host:organization:full_name': string;
      'host:organization:ogrn': string;
      'host:organization:kpp': string;
      'host:organization:registration_date': string;
      'host:organization:authorized_capital_k_rubles': number;
      'host:organization:legal_address': string;
      'host:organization:manager_name': string;
      'host:organization:main_activity': string;
    };
  };
  'notification': {
    plain: {
      'id': number;
      'status': string;
      'created_at': string;
      'delivered_at': string;
      'read_at': string;
      'type': string;
      'content': any;
      'organization_id': string;
      'recipient_id': number;
    };
    nested: {
      'organization': Schema['organization']['plain'] & Schema['organization']['nested'];
      'recipient': Schema['user']['plain'] & Schema['user']['nested'];
    };
    flat: {
      'organization:inn': string;
      'organization:short_name': string;
      'organization:full_name': string;
      'organization:ogrn': string;
      'organization:kpp': string;
      'organization:registration_date': string;
      'organization:authorized_capital_k_rubles': number;
      'organization:legal_address': string;
      'organization:manager_name': string;
      'organization:main_activity': string;
      'recipient:id': number;
      'recipient:email': string;
      'recipient:is_owner': boolean;
      'recipient:hashed_password': string;
      'recipient:phone': string;
      'recipient:full_name': string;
      'recipient:disabled': boolean;
      'recipient:is_admin': boolean;
      'recipient:is_verified_organization_member': boolean;
      'recipient:created_at': string;
      'recipient:organization_inn': string;
      'recipient:organization:inn': string;
      'recipient:organization:short_name': string;
      'recipient:organization:full_name': string;
      'recipient:organization:ogrn': string;
      'recipient:organization:kpp': string;
      'recipient:organization:registration_date': string;
      'recipient:organization:authorized_capital_k_rubles': number;
      'recipient:organization:legal_address': string;
      'recipient:organization:manager_name': string;
      'recipient:organization:main_activity': string;
    };
  };
  'order': {
    plain: {
      'id': number;
      'start_date': string;
      'end_date': string;
      'created_at': string;
      'updated_at': string;
      'status': string;
      'equipment_id': number;
      'requester_id': number;
    };
    nested: {
      'equipment': Schema['equipment']['plain'] & Schema['equipment']['nested'];
      'requester': Schema['user']['plain'] & Schema['user']['nested'];
      'ownerreview': Schema['ownerreview']['plain'] & Schema['ownerreview']['nested'];
      'renterreview': Schema['renterreview']['plain'] & Schema['renterreview']['nested'];
    };
    flat: {
      'equipment:id': number;
      'equipment:name': string;
      'equipment:description': string;
      'equipment:description_of_configuration': string;
      'equipment:with_operator': boolean;
      'equipment:price': number;
      'equipment:time_interval': string;
      'equipment:status': string;
      'equipment:year_of_release': number;
      'equipment:created_at': string;
      'equipment:updated_at': string;
      'equipment:added_by_id': number;
      'equipment:category_id': number;
      'equipment:organization_id': string;
      'equipment:added_by:id': number;
      'equipment:added_by:email': string;
      'equipment:added_by:is_owner': boolean;
      'equipment:added_by:hashed_password': string;
      'equipment:added_by:phone': string;
      'equipment:added_by:full_name': string;
      'equipment:added_by:disabled': boolean;
      'equipment:added_by:is_admin': boolean;
      'equipment:added_by:is_verified_organization_member': boolean;
      'equipment:added_by:created_at': string;
      'equipment:added_by:organization_inn': string;
      'equipment:added_by:organization:inn': string;
      'equipment:added_by:organization:short_name': string;
      'equipment:added_by:organization:full_name': string;
      'equipment:added_by:organization:ogrn': string;
      'equipment:added_by:organization:kpp': string;
      'equipment:added_by:organization:registration_date': string;
      'equipment:added_by:organization:authorized_capital_k_rubles': number;
      'equipment:added_by:organization:legal_address': string;
      'equipment:added_by:organization:manager_name': string;
      'equipment:added_by:organization:main_activity': string;
      'equipment:category:id': number;
      'equipment:category:name': string;
      'equipment:category:created_at': string;
      'equipment:category:verified': boolean;
      'equipment:category:added_by_id': number;
      'equipment:category:added_by:id': number;
      'equipment:category:added_by:email': string;
      'equipment:category:added_by:is_owner': boolean;
      'equipment:category:added_by:hashed_password': string;
      'equipment:category:added_by:phone': string;
      'equipment:category:added_by:full_name': string;
      'equipment:category:added_by:disabled': boolean;
      'equipment:category:added_by:is_admin': boolean;
      'equipment:category:added_by:is_verified_organization_member': boolean;
      'equipment:category:added_by:created_at': string;
      'equipment:category:added_by:organization_inn': string;
      'equipment:category:added_by:organization:inn': string;
      'equipment:category:added_by:organization:short_name': string;
      'equipment:category:added_by:organization:full_name': string;
      'equipment:category:added_by:organization:ogrn': string;
      'equipment:category:added_by:organization:kpp': string;
      'equipment:category:added_by:organization:registration_date': string;
      'equipment:category:added_by:organization:authorized_capital_k_rubles': number;
      'equipment:category:added_by:organization:legal_address': string;
      'equipment:category:added_by:organization:manager_name': string;
      'equipment:category:added_by:organization:main_activity': string;
      'equipment:organization:inn': string;
      'equipment:organization:short_name': string;
      'equipment:organization:full_name': string;
      'equipment:organization:ogrn': string;
      'equipment:organization:kpp': string;
      'equipment:organization:registration_date': string;
      'equipment:organization:authorized_capital_k_rubles': number;
      'equipment:organization:legal_address': string;
      'equipment:organization:manager_name': string;
      'equipment:organization:main_activity': string;
      'requester:id': number;
      'requester:email': string;
      'requester:is_owner': boolean;
      'requester:hashed_password': string;
      'requester:phone': string;
      'requester:full_name': string;
      'requester:disabled': boolean;
      'requester:is_admin': boolean;
      'requester:is_verified_organization_member': boolean;
      'requester:created_at': string;
      'requester:organization_inn': string;
      'requester:organization:inn': string;
      'requester:organization:short_name': string;
      'requester:organization:full_name': string;
      'requester:organization:ogrn': string;
      'requester:organization:kpp': string;
      'requester:organization:registration_date': string;
      'requester:organization:authorized_capital_k_rubles': number;
      'requester:organization:legal_address': string;
      'requester:organization:manager_name': string;
      'requester:organization:main_activity': string;
      'ownerreview:id': number;
      'ownerreview:rating': number;
      'ownerreview:comment': string;
      'ownerreview:created_at': string;
      'ownerreview:order_id': number;
      'renterreview:id': number;
      'renterreview:rating': number;
      'renterreview:comment': string;
      'renterreview:created_at': string;
      'renterreview:order_id': number;
    };
  };
  'organization': {
    plain: {
      'inn': string;
      'short_name': string;
      'full_name': string;
      'ogrn': string;
      'kpp': string;
      'registration_date': string;
      'authorized_capital_k_rubles': number;
      'legal_address': string;
      'manager_name': string;
      'main_activity': string;
    };
    nested: {};
    flat: {};
  };
  'ownerreview': {
    plain: {
      'id': number;
      'rating': number;
      'comment': string;
      'created_at': string;
      'order_id': number;
    };
    nested: {
      'order': Schema['order']['plain'] & Schema['order']['nested'];
    };
    flat: {
      'order:id': number;
      'order:start_date': string;
      'order:end_date': string;
      'order:created_at': string;
      'order:updated_at': string;
      'order:status': string;
      'order:equipment_id': number;
      'order:requester_id': number;
      'order:equipment:id': number;
      'order:equipment:name': string;
      'order:equipment:description': string;
      'order:equipment:description_of_configuration': string;
      'order:equipment:with_operator': boolean;
      'order:equipment:price': number;
      'order:equipment:time_interval': string;
      'order:equipment:status': string;
      'order:equipment:year_of_release': number;
      'order:equipment:created_at': string;
      'order:equipment:updated_at': string;
      'order:equipment:added_by_id': number;
      'order:equipment:category_id': number;
      'order:equipment:organization_id': string;
      'order:equipment:added_by:id': number;
      'order:equipment:added_by:email': string;
      'order:equipment:added_by:is_owner': boolean;
      'order:equipment:added_by:hashed_password': string;
      'order:equipment:added_by:phone': string;
      'order:equipment:added_by:full_name': string;
      'order:equipment:added_by:disabled': boolean;
      'order:equipment:added_by:is_admin': boolean;
      'order:equipment:added_by:is_verified_organization_member': boolean;
      'order:equipment:added_by:created_at': string;
      'order:equipment:added_by:organization_inn': string;
      'order:equipment:added_by:organization:inn': string;
      'order:equipment:added_by:organization:short_name': string;
      'order:equipment:added_by:organization:full_name': string;
      'order:equipment:added_by:organization:ogrn': string;
      'order:equipment:added_by:organization:kpp': string;
      'order:equipment:added_by:organization:registration_date': string;
      'order:equipment:added_by:organization:authorized_capital_k_rubles': number;
      'order:equipment:added_by:organization:legal_address': string;
      'order:equipment:added_by:organization:manager_name': string;
      'order:equipment:added_by:organization:main_activity': string;
      'order:equipment:category:id': number;
      'order:equipment:category:name': string;
      'order:equipment:category:created_at': string;
      'order:equipment:category:verified': boolean;
      'order:equipment:category:added_by_id': number;
      'order:equipment:category:added_by:id': number;
      'order:equipment:category:added_by:email': string;
      'order:equipment:category:added_by:is_owner': boolean;
      'order:equipment:category:added_by:hashed_password': string;
      'order:equipment:category:added_by:phone': string;
      'order:equipment:category:added_by:full_name': string;
      'order:equipment:category:added_by:disabled': boolean;
      'order:equipment:category:added_by:is_admin': boolean;
      'order:equipment:category:added_by:is_verified_organization_member': boolean;
      'order:equipment:category:added_by:created_at': string;
      'order:equipment:category:added_by:organization_inn': string;
      'order:equipment:category:added_by:organization:inn': string;
      'order:equipment:category:added_by:organization:short_name': string;
      'order:equipment:category:added_by:organization:full_name': string;
      'order:equipment:category:added_by:organization:ogrn': string;
      'order:equipment:category:added_by:organization:kpp': string;
      'order:equipment:category:added_by:organization:registration_date': string;
      'order:equipment:category:added_by:organization:authorized_capital_k_rubles': number;
      'order:equipment:category:added_by:organization:legal_address': string;
      'order:equipment:category:added_by:organization:manager_name': string;
      'order:equipment:category:added_by:organization:main_activity': string;
      'order:equipment:organization:inn': string;
      'order:equipment:organization:short_name': string;
      'order:equipment:organization:full_name': string;
      'order:equipment:organization:ogrn': string;
      'order:equipment:organization:kpp': string;
      'order:equipment:organization:registration_date': string;
      'order:equipment:organization:authorized_capital_k_rubles': number;
      'order:equipment:organization:legal_address': string;
      'order:equipment:organization:manager_name': string;
      'order:equipment:organization:main_activity': string;
      'order:requester:id': number;
      'order:requester:email': string;
      'order:requester:is_owner': boolean;
      'order:requester:hashed_password': string;
      'order:requester:phone': string;
      'order:requester:full_name': string;
      'order:requester:disabled': boolean;
      'order:requester:is_admin': boolean;
      'order:requester:is_verified_organization_member': boolean;
      'order:requester:created_at': string;
      'order:requester:organization_inn': string;
      'order:requester:organization:inn': string;
      'order:requester:organization:short_name': string;
      'order:requester:organization:full_name': string;
      'order:requester:organization:ogrn': string;
      'order:requester:organization:kpp': string;
      'order:requester:organization:registration_date': string;
      'order:requester:organization:authorized_capital_k_rubles': number;
      'order:requester:organization:legal_address': string;
      'order:requester:organization:manager_name': string;
      'order:requester:organization:main_activity': string;
      'order:renterreview:id': number;
      'order:renterreview:rating': number;
      'order:renterreview:comment': string;
      'order:renterreview:created_at': string;
      'order:renterreview:order_id': number;
    };
  };
  'renterreview': {
    plain: {
      'id': number;
      'rating': number;
      'comment': string;
      'created_at': string;
      'order_id': number;
    };
    nested: {
      'order': Schema['order']['plain'] & Schema['order']['nested'];
    };
    flat: {
      'order:id': number;
      'order:start_date': string;
      'order:end_date': string;
      'order:created_at': string;
      'order:updated_at': string;
      'order:status': string;
      'order:equipment_id': number;
      'order:requester_id': number;
      'order:equipment:id': number;
      'order:equipment:name': string;
      'order:equipment:description': string;
      'order:equipment:description_of_configuration': string;
      'order:equipment:with_operator': boolean;
      'order:equipment:price': number;
      'order:equipment:time_interval': string;
      'order:equipment:status': string;
      'order:equipment:year_of_release': number;
      'order:equipment:created_at': string;
      'order:equipment:updated_at': string;
      'order:equipment:added_by_id': number;
      'order:equipment:category_id': number;
      'order:equipment:organization_id': string;
      'order:equipment:added_by:id': number;
      'order:equipment:added_by:email': string;
      'order:equipment:added_by:is_owner': boolean;
      'order:equipment:added_by:hashed_password': string;
      'order:equipment:added_by:phone': string;
      'order:equipment:added_by:full_name': string;
      'order:equipment:added_by:disabled': boolean;
      'order:equipment:added_by:is_admin': boolean;
      'order:equipment:added_by:is_verified_organization_member': boolean;
      'order:equipment:added_by:created_at': string;
      'order:equipment:added_by:organization_inn': string;
      'order:equipment:added_by:organization:inn': string;
      'order:equipment:added_by:organization:short_name': string;
      'order:equipment:added_by:organization:full_name': string;
      'order:equipment:added_by:organization:ogrn': string;
      'order:equipment:added_by:organization:kpp': string;
      'order:equipment:added_by:organization:registration_date': string;
      'order:equipment:added_by:organization:authorized_capital_k_rubles': number;
      'order:equipment:added_by:organization:legal_address': string;
      'order:equipment:added_by:organization:manager_name': string;
      'order:equipment:added_by:organization:main_activity': string;
      'order:equipment:category:id': number;
      'order:equipment:category:name': string;
      'order:equipment:category:created_at': string;
      'order:equipment:category:verified': boolean;
      'order:equipment:category:added_by_id': number;
      'order:equipment:category:added_by:id': number;
      'order:equipment:category:added_by:email': string;
      'order:equipment:category:added_by:is_owner': boolean;
      'order:equipment:category:added_by:hashed_password': string;
      'order:equipment:category:added_by:phone': string;
      'order:equipment:category:added_by:full_name': string;
      'order:equipment:category:added_by:disabled': boolean;
      'order:equipment:category:added_by:is_admin': boolean;
      'order:equipment:category:added_by:is_verified_organization_member': boolean;
      'order:equipment:category:added_by:created_at': string;
      'order:equipment:category:added_by:organization_inn': string;
      'order:equipment:category:added_by:organization:inn': string;
      'order:equipment:category:added_by:organization:short_name': string;
      'order:equipment:category:added_by:organization:full_name': string;
      'order:equipment:category:added_by:organization:ogrn': string;
      'order:equipment:category:added_by:organization:kpp': string;
      'order:equipment:category:added_by:organization:registration_date': string;
      'order:equipment:category:added_by:organization:authorized_capital_k_rubles': number;
      'order:equipment:category:added_by:organization:legal_address': string;
      'order:equipment:category:added_by:organization:manager_name': string;
      'order:equipment:category:added_by:organization:main_activity': string;
      'order:equipment:organization:inn': string;
      'order:equipment:organization:short_name': string;
      'order:equipment:organization:full_name': string;
      'order:equipment:organization:ogrn': string;
      'order:equipment:organization:kpp': string;
      'order:equipment:organization:registration_date': string;
      'order:equipment:organization:authorized_capital_k_rubles': number;
      'order:equipment:organization:legal_address': string;
      'order:equipment:organization:manager_name': string;
      'order:equipment:organization:main_activity': string;
      'order:requester:id': number;
      'order:requester:email': string;
      'order:requester:is_owner': boolean;
      'order:requester:hashed_password': string;
      'order:requester:phone': string;
      'order:requester:full_name': string;
      'order:requester:disabled': boolean;
      'order:requester:is_admin': boolean;
      'order:requester:is_verified_organization_member': boolean;
      'order:requester:created_at': string;
      'order:requester:organization_inn': string;
      'order:requester:organization:inn': string;
      'order:requester:organization:short_name': string;
      'order:requester:organization:full_name': string;
      'order:requester:organization:ogrn': string;
      'order:requester:organization:kpp': string;
      'order:requester:organization:registration_date': string;
      'order:requester:organization:authorized_capital_k_rubles': number;
      'order:requester:organization:legal_address': string;
      'order:requester:organization:manager_name': string;
      'order:requester:organization:main_activity': string;
      'order:ownerreview:id': number;
      'order:ownerreview:rating': number;
      'order:ownerreview:comment': string;
      'order:ownerreview:created_at': string;
      'order:ownerreview:order_id': number;
    };
  };
  'user': {
    plain: {
      'id': number;
      'email': string;
      'is_owner': boolean;
      'hashed_password': string;
      'phone': string;
      'full_name': string;
      'disabled': boolean;
      'is_admin': boolean;
      'is_verified_organization_member': boolean;
      'created_at': string;
      'organization_inn': string;
    };
    nested: {
      'organization': Schema['organization']['plain'] & Schema['organization']['nested'];
    };
    flat: {
      'organization:inn': string;
      'organization:short_name': string;
      'organization:full_name': string;
      'organization:ogrn': string;
      'organization:kpp': string;
      'organization:registration_date': string;
      'organization:authorized_capital_k_rubles': number;
      'organization:legal_address': string;
      'organization:manager_name': string;
      'organization:main_activity': string;
    };
  };
};
